### ISSUE TITLE
Light Boxes

### ISSUE THREAD

**Issue by rajatthakur** [ccpandhare/bosm17-intro#1]
**General** 
1.Color of the lightbox should match with the current background image.
2.If I open a light box while a transition is taking place in the background, the animation gets paused in between.
3. Increase the opacity a little bit.

**Contact Us :**
1.Reduce the font size and align the text properly.
2.Remove the vertical scroll bars and refer to this: http://codepen.io/devstreak/pen/dMYgeO for the horizontal scroll bar.

**Sponsors:** 
Align the text with the center of logos.

**Travel**
Remove vertical scroll bar.

**Subscribe**

1. Change the font
2. Align the text properly.
3. Use a different style for subscibe button
4. The phone field should look like:     Phone: +91 |___textbox with max_length = 10______| i.e. +91 should be a part of the label itself. +91 is automatically appended at backend.

**Comment by rajatthakur** [comment]
@ccpandhare what is the status?? have you guys made the changes?

**Comment by ccpandhare** [comment]
Done by `Me` and `@nilay117 `
