### ISSUE TITLE
Reorder Contacts

### ISSUE THREAD

**Issue by rajatthakur** [ccpandhare/bosm17-intro#2]
Sports Sec should come first followed by Joint Sports Sec. and then the departments.

**Comment by rajatthakur** [comment]
Also add Vihang bhaiya at the end in the list of contacts.

**Comment by navjotbans** [comment]
/* done /*

**Comment by rajatthakur** [comment]
Great work !! work on the other issues that have been assigned to you.. :smile:

**Comment by madhurw7** [comment]
Change the font on the Contacts Page to Helvetica or Roboto. An All Caps should never be used for emails
